[package]
name = "web_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.23"
# full syn
syn = { version = "1.0.107", features = ["full"] }
